### ISSUE TITLE
Back end and API of the hosted authoring central

### ISSUE THREAD

**Issue by mvartanyan** [sphericalpm/lektorium#12]
The hosted authoring central is one of two main parts of Lektorium core. It provides non-technical users a possibility to edit content while keeping the results of their work consistent with the "lektory" web content as code ideology. 

The main idea of how it functions is that a Lektor instance is created each time the user wants to edit content of a given website; the instance is populated with the latest version of the website from the repo and hosted so the user can access it through the web. When the user is done with edits, they can stage changes: this creates a pull request against the staging branch. If the changes can be merged automatically, they get merged, otherwise the user is notified of a conflict. The user can destroy the instance, resync the instance from the repo, request promotion of changes to production, ... some idea of what the UI and the API will look like is available in [issue 10](https://github.com/sphericalpm/lektorium/issues/10)

## Architecture 

We will use docker containers to run multiple Lektor instances. 

In order to manipulate them from Python we will use [docker-py](https://docker-py.readthedocs.io/en/stable/index.html). 

To work with git, we will use **???**. 

### No state 

The Hosted Authoring central does not have its own state. State information for transactions it processes is coming from: 
- git
- state / metadata information of docker containers created

#### Input: 
- current user (from auth or ??? )

#### Output: 
- see "Available sites" example in [issue 10](https://github.com/sphericalpm/lektorium/issues/10)

#### Derivation:

Configuration files [issue 8](https://github.com/sphericalpm/lektorium/issues/8) in the Lektorium config repo. For the initial implementation, we can assume simple formats that could be swapped out later when we have the final format. 

Possible simple format:
- a known folder in the lekorium with site configuration files (/sites)
- each site config is an .ini file
- in the file there is an \[General\] section
- in the section, there is `repo` key a URL key with the URL to the site repo. Access is assumed and does not need to be verified
- there is also a `custodian` key with the user name of the custodian of the site.  
- there is an \[Editors\] section
- in the section, there are two keys: users=\<comma-separated user list\> and groups=\<comma-separated group list\>
- there is a \[Publishers\] section
- in the section, there are two keys: users=\<comma-separated user list\> and groups=\<comma-separated group list\>

For groups, there is a group configuration file in the Lektorium config repo (/groups.ini). The file is flat, \<group name\>= \<comma-separated user list\> . For now, we do not need to support nested groups. 

#### Input: 
- current user (from auth or ??? )

#### Output: 
- see "Edit sessions" example in [issue 10](https://github.com/sphericalpm/lektorium/issues/10)

#### Derivation:

Configuration files [issue 8](https://github.com/sphericalpm/lektorium/issues/8) in the Lektorium config repo (see previous point) and [labels](https://docs.docker.com/config/labels-custom-metadata/) of currently running Lektor containers. For the initial implementation, we can assume simple labelling conventions. 

Possible simple conventions:
editor=\<username\>
site=\<site name\>
url=\<url\>
status=\<draft|parked|staged|requesting_release\>

### List of Parked sessions

implementation is similar to the list of edit sessions. 

#### Input: 
- current user (from auth or ??? )

#### Output: 
- TBD example in [issue 10](https://github.com/sphericalpm/lektorium/issues/10)

#### Derivation:

implementation is similar to the list of edit sessions; the sessions to be listed are the ones requesting_release and belonging to any user as long as the current user is the Publisher for the site in question. 

#### Input: 
- current user (from auth or ??? )
- site id

#### Output: 
- success/failure (with reason)
- new instance url

#### Process:
- check that the user has the right to edit the site
- check that the user does not have another active (not parked) edit session
- create a new container
- check out the site's repo
- make Lektor admin interface and build location available on a user-accessible URL (how???)
- return the success report

#### Input: 
- current user (from auth or ??? )
- session id

#### Output: 
- success/failure (with reason)

#### Process:
- check that the session id belongs to the user
- check that the session is not already parked
- label the session container as parked 
- suspend Lektor admin interface (but not the build location!) (how???)
- return the success report

#### Input: 
- current user (from auth or ??? )
- session id

#### Output: 
- success/failure (with reason)

#### Process:
- check that the session id belongs to the user
- check that the session is parked
- check that there are no other active sessions for this site and user
- label the session container as draft
- enable Lektor admin interface (how???)
- return the success report

#### Input: 
- current user (from auth or ??? )
- session id

#### Output: 
- success/failure (with reason)

#### Process:
- check that the session id belongs to the user
- destroy the session container
- return the success report

#### Input: 
- current user (from auth or ??? )
- session id

#### Output: 
- success/failure (with reason)

#### Process:
- check that the session id belongs to the user
- create/activate a branch and commit the current state of the Lektor website from the container
- create a pull request / check for conflicts with the staging branch 
- check that there are no conflicts 
- merge the changes into the staging branch
- return the success report

#### Input: 
- current user (from auth or ??? )
- session id

#### Output: 
- success/failure (with reason)

#### Process:
- check that the session id belongs to the user
- suspend Lektor admin interface (but not the build location!) (how???)
- create/activate a branch and commit the current state of the Lektor website from the container
- create a pull request / check for conflicts with the staging branch 
- check that there are no conflicts 
- merge the changes into the staging branch
- label the container as staged
- return the success report

#### Input: 
- current user (from auth or ??? )
- session id

#### Output: 
- success/failure (with reason)

#### Process:
- check that the session id belongs to the user
- check that the container is staged
- label the container as requesting release
- notify the custodian (by email?)
- return the success report

#### Input: 
- current user (from auth or ??? )
- session id

#### Output: 
- success/failure (with reason)

#### Process:
- check that the container is requesting release
- check that the current user is a publisher for the container's site
- create a pull request / check for conflicts with the master branch 
- check that there are no conflicts 
- merge the changes into the master branch
- notify the owner (by email?)
- destroy the container
- notify the custodian 
- return the success report

**Comment by AndreiDrang** [comment]
Long term tasks(like git and docker commands) will be moved to separate Celery tasks.
With Celery we will use RabbitMQ or Redis and Flower.

**Comment by igor35hh** [comment]
after reading this, maybe we should think more one time about  stack and use something async

**Comment by AndreiDrang** [comment]
For what?

**Comment by igor35hh** [comment]
> For what?

for this project

**Comment by AndreiDrang** [comment]
> after reading this, maybe we should think more one time about stack and use something async

Cause `Celery` it is not only async task manager. It is useful and helpful architecture around it.

**Comment by apatrushev** [comment]
Irrelevant anymore
