### ISSUE TITLE
Lektoruim git module

### ISSUE THREAD

**Issue by katridi** [sphericalpm/lektorium#15]
We need to implement the functionality which will allow Lektorium to work with git repositories

Here are the main functions that the module should be able to do.
- create new branch in git repository
- commit the changes
- push commits to git repository
- try to merge the changes and return result of merging

Consider using https://gitpython.readthedocs.io/en/stable/index.html or through git itself

**Comment by katridi** [comment]
- [ ] catch and handle exceptions in every function in Repository class
- [x] add in logging stacktrace
- [ ] add more test cases 
- [ ] add "megre --abort" in merging function  in Repository class
- [x] add docstrings to every function and class

**Comment by apatrushev** [comment]
Irrelevant anymore
