### ISSUE TITLE
Lektorium Python Docker interface

### ISSUE THREAD

**Issue by AndreiDrang** [sphericalpm/lektorium#16]
Add Docker client(based on `docker-py`), which will complete following tasks:
- [x] Create image from `Lector` website;
- [x] Run container with `Lector` website;
- [x] Stop container with `Lector` website;
- [ ] Check runned `Lector` container website status;
- [x] Removing unused images and containers automatically.

**05.08.19 - UPDATE**
- [x] Move all functions in class methods;
- [x] Add tests;
- [ ] Change sync library to async.

**06.08.19 - UPDATE**

- [ ] Change Dockerfile default image, from `Ubuntu 18.04` to smth lightweight.

After prototype creating, these functions will be added to separate `Lectorium` Celery tasks and runned by the user from UI.

**Comment by apatrushev** [comment]
Why you decided to use docker-py but not aiodocker?

**Comment by mvartanyan** [comment]
My understanding that the use of queues is a post-prototype consideration, the prototype implementation will be synchronous/blocking, right?

**Comment by AndreiDrang** [comment]
> My understanding that the use of queues is a post-prototype consideration, the prototype implementation will be synchronous/blocking, right?

Yep

> Why you decided to use docker-py but not aiodocker?

Cause we will use Celery to run docker-tasks async, and all will be ok, i think.

**Comment by apatrushev** [comment]
> Cause we will use Celery to run docker-tasks async, and all will be ok, i think.

It is not an answer. The problem is that you can wait for completion of asynchronous code, but with the blocking code you can not do anything in async env.

**Comment by AndreiDrang** [comment]
It is answer, cause in sync way i can time to time check async task status and working with result.

**Comment by apatrushev** [comment]
> It is answer, cause in sync way i can time to time check async task status and working with result.

My intention is just to warn you about potential future consequences of such decision. If you will work with async-aware library you can easily work with it in both environments sync/async. Otherwise you will stuck forever to blocking approach.

**Comment by apatrushev** [comment]
Irrelevant anymore
