### ISSUE TITLE
Repository parser module

### ISSUE THREAD

**Issue by mjecov** [sphericalpm/lektorium#24]
We need to realized a module with the following functionality:

- Parsing the config data from downloaded repository
- Getting the Lektor folder which will be runned.

**Comment by perevertysh** [comment]
Which is format of config file ? What needs check in rep at first?

**Comment by zillent** [comment]
I proposed it in https://github.com/sphericalpm/lektorium/issues/8.
Waiting any comments

**Comment by apatrushev** [comment]
Irrelevant anymore
