### ISSUE TITLE
API to interact with the web interface

### ISSUE THREAD

**Issue by mjecov** [sphericalpm/lektorium#25]

**Comment by AndreiDrang** [comment]
First iteration:
1. Create core aiohttp app with minimum two nested apps.
2. First nested app - authentication app. Full cycle(login/logout/cookies timeout).
3. Second nested app - api with methods from issue #12 (requirements list), replace logic with stubs which check user auth and return empty results.

**Comment by apatrushev** [comment]
Irrelevant anymore
