### ISSUE TITLE
Brainstorm site configuration parameters

### ISSUE THREAD

**Issue by mvartanyan** [sphericalpm/lektorium#8]
We need to come up with a data structure for site configuration parameters. There are obvious things such as: 

- site root domain/location name
- repo name to keep the site source code
- list of users / user groups allowed to administer the site
- list of users / user groups allowed to edit content on the site 

but the actual list of individual site config parameters is likely longer. Continue in comments.

**Comment by mvartanyan** [comment]
- member access restrictions to be deployed (paths -> users/groups)

**Comment by zillent** [comment]
I think, it would be better save this settings into database. Something like SQLite. Especially for users/groups.

**Comment by AndreiDrang** [comment]
Yep, sqlite will be best idea to store most of this data.
But 2 first things(and maybe better) can be stored in site `yml-config-file`(or in other file format, which we will choice).

**Comment by mvartanyan** [comment]
Ideally, Lektorium will be completely stateless, with little, short-lived cache of what it observes in git and docker living in memory. This issue was meant to brainstorm **what** we need to store about sites, not where.

**Comment by zillent** [comment]
Example of site config. Any suggestions? :-)

[example.com.yaml](https://github.com/sphericalpm/lektorium/files/3428192/example.com.yaml.txt)

**Comment by apatrushev** [comment]
Irrelevant anymore
